### ISSUE TITLE
Feature: User can like or dislike a work of art

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/ajax-project#1]
## ⚙️ Feature

User can mark a work of art as one they like or one they dislike.

## 📐 Functionality

On the landing screen, users will be presented with a button that, when clicked, pulls a random image and gives the user two button options, Like and Dislike. Clicking like saves data about the painting. Clicking either button brings up a new image.

## 🖼️ Wireframes

![1](https://user-images.githubusercontent.com/21215658/173471341-5c7e74a0-4169-4825-8f9b-b572e2d14280.PNG)
![2](https://user-images.githubusercontent.com/21215658/173471344-6f7f707e-3d82-4a75-976e-f11faf0c79c4.PNG)
![1_mobile](https://user-images.githubusercontent.com/21215658/173492491-6e48eebb-e9d8-4afa-8eef-d69dd1f64820.PNG)

## ✅ Task List

- [x] Create a view for the landing page with HTML and CSS
- [x] Add hover and click properties for the button in line with Material UI guidelines
- [x] Create a view for liking/disliking images, with styling for the buttons
- [x] Constrain the image to be within a box of fixed height
- [x] Add an event listener to the orange button to switch the view to the like/dislike view
- [x] Add an event listener on the logo area to switch the view to the landing view
- [x] Create data object to store shown image object ids, liked images, disliked images
- [x] Write a function to get a random image from the API
  - [x] Function should check that a `primaryImageSmall` exists and try again if there is no image
  - [x] ~~Function can save all returned info for now~~
  - [x] Function should exclude previously shown images based on `objectId`
- [x] Add event listeners to both like and dislike buttons which get a new random image and set the displayed image to the new image
  - [x] Include code to store the artwork's data in the appropriate property in the data object
- [x] Create a data object to store both liked images and disliked images
- [x] ~~Write a function that appends artwork data to the data object (parameter to determine like or dislike)~~ (unnecessary level of complication)
- [x] Add this function to the like and dislike button event listeners
- [x] Shuffle array of object ids before iterating through for more "random" experience
- [x] Keep 10 works of art with images loaded, and update the image using this cache of images
- [x] Add breakpoints for mobile view
- [x] Add CSS class definitions that will apply in mobile view
- [x] Test everything in desktop and mobile views
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by dennisliu9** [comment]
Note: Persisting to local storage is **not** included in this feature
