### ISSUE TITLE
Feature: User can remove Liked artwork.

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/ajax-project#12]
## ⚙️ Feature

Users can change their mind or change their feelings toward a work of art, and in turn remove it from their My Likes pane.

## 📐 Functionality

On the My Likes sheet, there is a delete icon which toggles Delete Mode. In delete mode, clicking on an image in the gallery brings up a prompt to reconsider the artwork: send it to the list of Dislikes or keep it in Likes.

## 🖼️ Wireframes

![desktop1](https://user-images.githubusercontent.com/21215658/175487428-0fb90ab6-9e82-4581-ad7d-25048f87b0f0.PNG)
![desktop2](https://user-images.githubusercontent.com/21215658/175487437-2b6a5173-df82-4fc2-b739-3e43c567d409.PNG)
![mobile](https://user-images.githubusercontent.com/21215658/175487440-b5289f9c-766a-42a9-bb94-4ea8a57f3466.PNG)

## ✅ Task List

- [x] Add Delete icon to bottom sheet
- [x] Add event listener and CSS classes that toggles it On/Off on click
- [x] Set a global variable to indicate if user is on Delete Mode or not (with corresponding visual toggle)
- [x] Create a confirm deletion modal with buttons and empty image container and element
- [x] Create a property in the `data` object to store the index of the clicked (i.e., to be deleted) object
- [x] Adjust gallery image click handler function to check if in delete mode
  - [x] Query for the delete modal container
  - [x] Query for the delete modal image
  - [x] If delete mode is false, keep current functionality
  - [x] If delete mode is true, remove class `hidden` from the delete modal
- [x] Populate the image in the modal with clicked image
- [x] Save the DOM object for the clicked image in the gallery to a variable
- [x] Add event listeners to buttons
  - [x] Dislike/Delete button moves current object into `data.dislikedObjects`
  - [x] Dislike/Delete button removes the DOM object from the tree for the gallery
  - [x] Like button just closes the modal
  - [x] Both buttons reset the field that was holding the "to be deleted" index
- [x] Revise button setup so that they appear on top of each other on mobile
- [x] Add hovering message to indicate Delete Mode has been turned on
- **Debug**
- [x] Revise cache number to be at least 5
- [x] Write function to check if keys of `data` from local storage matches the expected format of `data`, and clear `localStorage` if not
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by dennisliu9** [comment]
Fix mobile scroll issues in next feature
