### ISSUE TITLE
Feature: User can see artwork details

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/ajax-project#17]
## ⚙️ Feature

Users can see information commonly displayed on a placard next to an artwork in a museum.

## 📐 Functionality

In the detail view, there will be a clickable "info" icon which will toggle the placard information beneath the artwork. Their toggle selection remains active for all artworks in detail view until they toggle it off.

## 🖼️ Wireframes

![desktop](https://user-images.githubusercontent.com/21215658/175804653-36883c85-40bf-48fe-a198-879f182ab42e.PNG)
![mobile](https://user-images.githubusercontent.com/21215658/175804329-01e3cafe-4b76-4a2a-803a-caa582ec7e3e.PNG)

## ✅ Task List

- [x] Add info icon to the right of the detail image modal
  - [x] Icon should be positioned such that the artwork remains centered on the screen
- [x] Add a text element for the information that is left aligned to the "main app area" container, below the image
- [x] Modify detail window click handler to allow modal closing given the new HTML elements created to show the detail info
- [x] Write a function that creates the necessary text from the `data.viewingInDetail` property
- [x] On the event handler function for entering the detail view, call the text generating function and populate the info text element
  - [x] Create a hyperlink using `objectUrl` to link to the Met's website
- [x] ~~Add a global variable to store whether the info toggle is `true` or `false` (initialize with `false`)~~ Not necessary, just toggle classes
- [x] Create an event listener on the info icon that toggles the visibility of the info text element
- [x] Add sizing classes to elements in placard
- [x] Double check mobile view and desktop view
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by dennisliu9** [comment]
![ajax-project_feature-5_view-info_desktop1_solution](https://user-images.githubusercontent.com/21215658/175996861-c75f3397-adfa-40fd-8a49-04d49764daaa.gif)
![ajax-project_feature-5_view-info_desktop2_solution](https://user-images.githubusercontent.com/21215658/175996867-e8b1f73b-7331-4151-bba8-174dedf3ec9e.gif)
![ajax-project_feature-5_view-info_mobile_solution](https://user-images.githubusercontent.com/21215658/175996869-8aa8ff3d-2cbc-4248-9ff1-b72056c41f17.gif)
