### ISSUE TITLE
Polish User Interfaces

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/ajax-project#19]
## ✅ Task List

- [x] Ensure all clickable elements have a `pointer` cursor
- [x] Where applicable, modify the appearance of clickable elements on hover
- [x] Fix issues with mobile interface
  - [x] Find laptop's IP address with `ipconfig`
  - [x] Access live server using mobile phone(s) to ensure changes are working properly
- [x] Using the responsive view in Dev Tools, ensure website never looks broken
- [x] Remove placeholder links and buttons
- **Network**
  - [x] ~~Replace "image loading" image with a loading spinner~~ Add blur overlay with spinner over placeholder image
  - [x] ~~Apply loading spinner when images are loading (How can I tell an image has been loaded? I see it loaded in the Network tab of Dev Tools)~~ Put this off for now, may be easier if ajax requests are done with `fetch`
  - [x] Apply loading spinner when images are being queued
  - [x] Ensure app continues as intended when API request returns a 404
  - [x] Handle network request errors
- [x] (Bonus): Randomly cycle through color palettes for spinner
