### ISSUE TITLE
Feature: User can choose to see a new work of art similar to their liked artwork.

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/ajax-project#2]
## ⚙️ Feature

Users will have the ability to toggle between completely random works of art or works of art that have some similarities to the artwork they have already liked, allowing them to explore their interests more deeply.

## 📐 Functionality

On the landing view and the like/dislike view, there will be two chip buttons under the main button(s). One is for "Random" and the other is for "Similar" which will affect the next image shown. This selection persists between images, and can be changed at any moment.

## 🖼️ Wireframes

![1](https://user-images.githubusercontent.com/21215658/173493432-1a4a15f6-2068-488f-89ef-7fa793456391.PNG)
![1_mobile](https://user-images.githubusercontent.com/21215658/173493437-c706623a-604f-41e0-86fe-b91658cbc023.PNG)

## ✅ Task List

- [x] Add text and chip button text to main app area, but outside the `landing` and `selection` sections so that text and chip buttons appear on both views
- [x] Add and apply CSS styles for chip buttons (selected and deselected)
- [x] Set up chip buttons for radio-button-like behavior
  - [x] Use a class or `div` to make them selectable as a group
  - [x] Event listener applies "selected" styling class to clicked chip button, "deselected" the the rest (only one other for now)
  - [x] Add some `data` attribute to the chip button that can be assigned to a global variable in JavaScript, used to determine what search to use
- [x] Logic for similar search
  - [x] Create a new data object named `metadata` with structure like example below
  - [x] Write a function that inserts data and counts based on objects stored in `data.likedObjects`
  - [x] Write a function to randomly grab `n` number of keys in `metadata.likedMetadata`
    - [x] If one of the keys is `geoLocation`, proceed to grab one random key in `geoLocation`
  - [x] Write a function to randomly pick up to `m` number of keys within each of the `n` keys (e.g. pick 3 artists from `artistDisplayName`), **weighted by counts for each key**
    - [x] (Bonus) Incorporate dates if possible
  - [x] Write the URL search section with parameters for the keys selected and picked values concatenated
  - [x] (Special cases) Consider what to do with "Untitled" and "Unknown Artist" and other variations of unknown information
- [x] Add parameter for searching Met API that uses random or "similar" string
  - [x] Based on this parameter, use one string or the other
  - [x] To check that functionality is working as expected, `console.log` the URL
  - [x] Should a URL with a set of search parameters be used for just one artwork and discarded? Or should the results be used until the array is empty? (latter saves requests, former is easier to insert into existing logic and appears more random to the user) (Resolution: one and then discarded)
- [x] How to clear out and repopulate pre-load cache between random and similar selections? Two separate caches? (Use one cache, prepend new results to the array rather than append)
- [x] (Data Issue) Add the department ID used to search for an artwork to the artObj it is stored as. This is different from the `department` field on the object returned from the API call
- **Debug**
- [x] Revise CSS rules to use `100%` height instead of `100vh` to overcome mobile issues (address bar taking up some `vh`)
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

## Example `metadata` Format

```javascript
metadata = {
  likedMetadata: {
    isHighlight: {
      true: 35,
      false: 65
    },
    departmentId: {
      1: 20,
      3: 42,
      7: 48
    },
    // for artistOrCulture search
    artistDisplayName: {
      'Vincent van Gogh': 12,
      'Henri Matisse': 8,
      'Jackson Pollock': 15,
      'Piet Mondrian': 5,
      'Jean-Michel Basquiat': 14,
      'Pablo Picasso': 6,
      'Georges Seurat': 1,
      'Michelangelo': 5,
      'Keith Haring': 6,
      'Auguste Renoir': 4,
      'Edgar Degas': 4,
      'Claude Monet': 20
    },
    culture: {
      Afghan: 33,
      British: 33,
      'North African': 34
    },
    medium: {
      'Ceramics': 10,
      'Furniture': 20,
      'Paintings': 45,
      'Sculpture': 25
    },
    geoLocation: {
      city: {
        'New York': 28,
        'Paris': 42,
        'Tokyo': ...
      },
      state: {
        'Alamance': 15,
        'Derbyshire': 8,
        'Brooklyn': ...
      },
      county: {
        'Orange County': 3,
        'Staffordshire': 9,
        'Brooklyn': ...
      },
      country: {
        'China': 9,
        'France': 15,
        'India': ...
      },
      region: {
        ...
      },
      subregion: {
        ...
      }
    },
    dateBegin: {...},
    dateEnd: {...}
  }
  // dislikedMetadata in the future
}
```
