### ISSUE TITLE
Polish - Speed Up Material Icons Package

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/ajax-project#22]
## ❌ Problem

Material icons stylesheet takes very long to load (multiple megabytes). Very noticeable flaws on slower internet connections.

## ✅ Task List

- [ ] Find equivalent/similar replacements for Material Icons through Font Awesome
- [ ] Swap out icons
- [ ] Ensure icons look the same (same styling is applied)
- [ ] Remove Material Icons stylesheets and styling from HTML
