### ISSUE TITLE
Feature: User can see a list/grid of the art they liked.

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/ajax-project#3]
## ⚙️ Feature

Users can open a pane of the images they have marked as "Liked" to reference and enjoy again.

## 📐 Functionality

A pane/sheet that is partially visible at the bottom of the page can be opened to fill the view area with a grid of liked images (a list on mobile). Clicking on one of the images brings it into a modal view where it can be viewed at larger resolution.

## 🖼️ Wireframes

![1](https://user-images.githubusercontent.com/21215658/173495666-737778d7-5512-4cdf-b912-9fa095610ab7.PNG)
![1_mobile](https://user-images.githubusercontent.com/21215658/173495679-33e2a3ed-cb5e-4ffd-bd9d-a184d03f3893.PNG)

## ✅ Task List

- **Create Sheet**
- [x] Create a `div` to hold the "My Likes" bottom sheet and set the width of the `div` to match the container (use `col-full`)
- [x] Set the height to be the height of the viewport, but excluding the header
  - [x] This may involve `overflow-y:auto;` to get the sheet scrollable without adjusting the rest of the page
- [x] Add a row to act as a header at the top of the bottom sheet
- [x] Add the text "My Likes" to the header
- **Render Images**
- [x] Use DOM manipulation to create `img` elements in the sheet from the `data` object
- [x] Create and apply CSS classes so that there are 3 pictures to a row on desktop, 2 on tablet, and 1 on mobile
- [x] Add functionality to render image as soon as a user clicks Like
- **Toggle Sheet**
- [x] Use CSS classes to set the bottom sheet's positioning to ~~`fixed`~~ `absolute` so that it can sit on top of the rest of the page and be translated up and down, while still not moving when scrolling up and down the page
  - [x] Use `overflow: hidden` to prevent scrolling on outside content
- [x] Use a CSS class to translate the sheet down into a "minimized" position
- [x] Use event listeners on the header row to toggle the minimized position
- [x] Add an X icon to the right side of the header for a close button
- [x] Hide the X button when sheet is minimized
- [x] Adjust the event listener to only hide the sheet when the X is closed but still allow it to expand anywhere on the header row
- [x] Add line decoration to the top of the bottom sheet to indicate it's something that can be expanded upon clicking
- **Detail Modal**
- [x] Create hidden modal screen with an image element
- [x] Add event listener for clicks on overlay to close the modal
- [x] Clicking on an image in the sheet brings up ~~the `primaryImage` property (full size) inside of a modal~~ the image in the modal
  - [x] Include ability to close the modal
- [x] Clicking on an image in the modal opens a new window/tab to full size image
- **Quality of Life**
- [x] Prevent `<a>` elements from jumping to the top
- [x] Add local storage saving functionality
  - [x] Add override function that clears local storage and sets a flag to stop stringifying from happening
- **Debug**
- [x] Prevent users from clicking orange start button before departments are loaded
  - [x] Create a function to run start up functions, of which getting departments is one of them
  - [x] Add a CSS style for disabled orange button and make it the default (`.button-main-disabled`)
  - [x] On departments being loaded change styling back to orange (back to `.button-main`)
  - [x] ~~Move event listener for start button clicks to after button styling changes~~ Event listener to check if button has disabled class
- [x] Fix issue where Like/Dislike button are too close/covered by bottom sheet, even when minimized
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by dennisliu9** [comment]
![ajax-project_feature-2_desktop_solution](https://user-images.githubusercontent.com/21215658/174413575-16d084a5-11e3-4cbc-b6b2-f5417f41cd21.gif)
![ajax-project_feature-2_mobile_solution](https://user-images.githubusercontent.com/21215658/174413578-76c039c8-af37-4890-938d-b1f4504b287b.gif)

**Comment by dennisliu9** [comment]
In a future revision, change bottom sheet animation to use this (from LinkedIn's messaging bubble pane)
`transition: transform 167ms cubic-bezier(.4,0,1,1) 0ms;`
