### ISSUE TITLE
Feature: User can see the metadata breakdown of the art they liked.

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/ajax-project#4]
## ⚙️ Feature

Users can see a list of the attributes for the artwork they have liked to help inform them what sort of art they tend to like.

## 📐 Functionality

The Liked images pane/sheet will have an additional button that brings in a side panel which displays some relevant tags of the liked artwork along with the counts for each tag. Tags are ordered by category, then by counts.

## 🖼️ Wireframes

![1](https://user-images.githubusercontent.com/21215658/173497364-57250b4a-1cbd-40fd-82e0-1b9216d73b21.PNG)
![1_mobile](https://user-images.githubusercontent.com/21215658/173497366-f54c8bed-0821-4136-a8be-eaeca2c0b03d.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ]
- [ ]
- [ ]
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
