### ISSUE TITLE
Feature: User can filter their liked artworks by metadata.

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/ajax-project#5]
## ⚙️ Feature

Users can click on the metadata tags in the side panel to filter the results, giving an additional way to explore art.

## 📐 Functionality

Under the tags pane, the metadata tags are now clickable. Multiple can be selected in each category, and the filtering is done as soon as the tag is clicked. Other tags update with revised counts as the results narrow. If the side pane is closed without clearing the filters, the filters persist.

## 🖼️ Wireframes

![1](https://user-images.githubusercontent.com/21215658/173497912-c418f9aa-8ae6-4595-9f5b-0040f1fa780d.PNG)
![1_mobile](https://user-images.githubusercontent.com/21215658/173497915-f3514ee6-654d-432e-a015-9c2706114de8.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] 
- [ ] 
- [ ] 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
